### ISSUE TITLE
Plugin Incompatible with WooCommerce – MailerLite plugin due to name space issue

### ISSUE THREAD

**Issue by lukecav** [closemarketing/connector-gravityforms-mailerlite#1]
When this plugin is used in conjunction with Mailerlite’s native woocommerce connector it results in a PHP failure:

`2019/08/08` 13:38:27 [error] 2066#2066: *353900 FastCGI sent in stderr: “PHP message: PHP Fatal error: Cannot redeclare Clue\StreamFilter\register() (previously declared in /www/XXX/public/wp-content/plugins/connector-gravityforms-mailerlite/vendor/clue/stream-filter/src/functions.php:140) in /www/XXX/public/wp-content/plugins/woo-mailerlite/vendor/clue/stream-filter/src/functions.php on line `127”`

https://wordpress.org/support/topic/plugin-incompatible-with-woocommerce-mailerlite/
https://github.com/mailerlite/woo-mailerlite
https://wordpress.org/plugins/woo-mailerlite/

**Comment by davidperezgar** [comment]
Hello, I'll see it and solve in next version.
